### ISSUE TITLE
The flag --parent-path seems useless

### ISSUE THREAD

**Issue by beeleelee** [filedrive-team/go-graphsplit#9]
Seems --parent-path always has same value the the target, so why just ignore --parent-path?

**Comment by qianhh** [comment]
I want to keep this feature, because the following functions cannot be implemented without this parameter. For example, if I want to split a subdirectory of a directory, but I also want to keep its root directory, I can do this:
```sh
./graphsplit chunk \
--car-dir=path/to/car-dir \
--slice-size=17179869184 \
--parallel=2 \
--graph-name=gs-test \
--parent-path=/path/to/dataset \
/path/to/dataset/subdir
```
What would I do without this feature? Can we set a default parameter to make --parent-path the same as the directory we specified for the split?

**Comment by beeleelee** [comment]
I got your point @qianhh . Sounds rational. Ok, I'll keep the --parent-path flag.
